dist: trusty
sudo: false

before_install:
  - apt-get install libffi-dev
  - curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
  - source $HOME/.pythonz/etc/bashrc
  - pythonz install 2.7.13
