language: python
dist: trusty
sudo: required

env:
  global:
      - MAKEFLAGS="-j 2"

before_cache:
  - rm -rf $HOME/.pythonz/build/*
  - rm -rf $HOME/.pythonz/log/*
  - du -sh $HOME/.pythonz
cache:
  directories:
    - "$HOME/.pythonz"

matrix:
  include:
    - os: osx
      language: objective-c
    - os: linux
      dist: trusty

before_install:
  - if [[ ! -s $HOME/.pythonz/etc/bashrc ]]; then  curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash; fi
  - source $HOME/.pythonz/etc/bashrc

install:
  - pythonz install 2.6.9
  - pythonz install 2.7.13
  - pythonz install 3.2.5
  - pythonz install 3.3.6
  - pythonz install 3.4.6
  - pythonz install 3.5.3
  - pythonz install 3.6.1
  - pythonz install -t pypy 5.3.1
  - pythonz install -t pypy3 2.3.1
  - pythonz install -t pypy3 2.4.0

script:
  - env
  - pythonz list
  - .travis/run.sh
