matrix:
  include:
    - os: windows
      language: bash

before_install:
  - export OLDPATH=$PATH
  - mkdir -p /c/pythons
  
  - wget https://www.python.org/ftp/python/3.6.7/python-3.6.7-amd64.exe
  - python-3.6.7-amd64.ext /quiet InstallAllUsers=1 TargetDir=C:\\pythons\\Python36-x64 Include_test=0 AssociateFiles=0
  - /c/pythons/Python36-x64/python -m pip install --upgrade pip setuptools

install:
  - git clone --recursive https://github.com/ifduyue/python-xxhash.git
  - pushd python-xxhash
  - export PATH="/c/pythons/Python36-x64:/c/pythons/Python36-x64/Scripts:$OLDPATH"
  - python setup.py build_ext

script:
    - python setup.py test
