language: bash

matrix:
  include:
    - os: windows

install:
  - git clone --recursive https://github.com/ifduyue/python-xxhash.git
  - pushd python-xxhash
  - python setup.py build_ext

script:
  - python setup.py test
