dist: trusty
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential zlib1g-dev libbz2-dev libssl-dev libreadline-dev libncurses5-dev libsqlite3-dev libgdbm-dev libdb-dev libexpat-dev libpcap-dev liblzma-dev libpcre3-dev
  - curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
  - rehash
  - pythonz install 2.7.13
