matrix:
  include:
    - os: windows
      language: cpp

before_install:
  - export OLDPATH=$PATH
  - mkdir -p /c/pythons
  - choco install -y vcpython27
  - choco install -y visualstudio2017buildtools
  - choco install python2 --version 2.7.15 -my --params "/InstallDir:C:\\pythons\\Python27-x64"
  - choco install python2 --version 2.7.15 -my --x86 --params "/InstallDir:C:\\pythons\\Python27"
  - choco install python2 --version 2.6.6 -my --params "/InstallDir:C:\\pythons\\Python26-x64"
  - choco install python2 --version 2.6.6 -my --x86 --params "/InstallDir:C:\\pythons\\Python26"
  - choco install python3 --version 3.7.1 -my --params "/InstallDir:C:\\pythons\\Python37-x64"
  - choco install python3 --version 3.7.1 -my --x86 --params "/InstallDir:C:\\pythons\\Python37"

install:
  - git clone --recursive https://github.com/ifduyue/python-xxhash.git
  - pushd python-xxhash
  - export PATH="/c/pythons/Python27-x64:/c/pythons/Python27-x64/Scripts:$OLDPATH"
  - python setup.py build_ext

script:
    - python setup.py test
