os: windows
language: c

install:
  - choco install python3
  - python3 -m pip install --upgrade pip setuptools cibuildwheel
  - git clone https://github.com/redis/hiredis-py.git
  - pushd hiredis-py
  - cibuildwheel --output-dir wheels
  - ls wheels
