matrix:
  include:
    - os: windows
      language: bash

before_install:
  - export OLDPATH=$PATH
  - mkdir -p /c/pythons
  - choco install python2 --version 2.7.15 -my --install-directory C:\\Python27-x64 
  - choco install python2 --version 2.7.15 -my --x86 --install-directory C:\\Python27
  - choco install python2 --version 2.6.6 -my --install-directory C:\\Python26-x64 
  - choco install python2 --version 2.6.6 -my --x86 --install-directory C:\\Python26

install:
  - git clone --recursive https://github.com/ifduyue/python-xxhash.git
  - pushd python-xxhash
  - export PATH="/c/pythons/Python27-x64:/c/pythons/Python36-x64/Scripts:$OLDPATH"
  - python setup.py build_ext

script:
    - python setup.py test
